### ISSUE TITLE
'No Collection Allocated' modules appear across all collections when in live/student view

### ISSUE THREAD

**Issue by HenryGriff** [djplaner/canvas-collections#167]
This behavior would mirror 'edit' mode behavior.

Example being a Lectures module should be available across all collections, these collections are structured around tutorial leads but all share lecture content - https://lms.griffith.edu.au/courses/8287/modules#cc-collection-1

**Comment by djplaner** [comment]
# Planning

## Background - vanilla

`CollectionsView::showCanvasModules` implements the hide/show of Canvas modules. A simple change should work.

- [ ] How will this impact labels and auto nums?

## Design - vanilla

- [ ] Implement change in showCanvasModules
- [ ] Test with labels and auto nums


## Background - svelte


## Design - svelte

**Comment by djplaner** [comment]
# Implement an "include unallocated" switch

Add `includeUnallocated` to each collection to store value.  means that students won't see it.
 
- [ ] ensure `includeUnallocated` is included in collections and is true
- [ ] update `CollectionsConfiguration` to display and change the value
- [ ] add help documentation and link
