### ISSUE TITLE
Progress notification bar overlaps Engage button at approx 1360px

### ISSUE THREAD

**Issue by davemart30** [djplaner/canvas-collections#27]
Might be able to use breakpoints to shrink button as window width decreases. Only a visual issue as Engage link still works even when progress bar and Engage overlap.

**Comment by djplaner** [comment]
Yea, known problem @davemart30.  

Entirely a result of taking the CSS from the [card interface](https://github.com/djplaner/Card-Interface-Tweak) designed for Bb and plonking it holus bolus into Canvas with no modification.

If this goes beyond a prototype, one of the first steps will be to redesign the card interface to work better with Canvas and also to be more accessible.

The plus for canvas-collections is that the code is vastly more flexible. There's structure already in place to easily add different views/representations.  e.g. I've plans on experimenting with adding a "learning journey" view #25

**Comment by djplaner** [comment]
Moved on a fair bit since these days.  Progress bar not currently included in current representations, but on the drawing board
