### ISSUE TITLE
Horizontal Cards Presentation not displaying correctly 

### ISSUE THREAD

**Issue by omachado-id** [djplaner/canvas-collections#296]
Hi, 
Just reporting some odd behavior using the **Horizontal Cards** presentation method not working correctly within a short training course for our faculty, in which I've decided to use Canvas Collections:

**Description**
The course consists of 5 instructional material modules, each with differing content/purposes.  I therefore decided to give each module its own Collection, with a distinct Include page for each Collection.  I also decided to use the horizontal card presentation.  It's this presentation method that's not working as expected.

When I created the first Collection, the horizontal card presentation worked correctly and displayed the correct Include page.  However, when I assigned a module to the second (and subsequent) collections, the horizontal cards view were showing the incorrect Collections' horizontal cards, and displayed the (pictured) error stating that no Collection's had been allocated for that module (thought they had been within the panel where Collections and Includes are assigned and named.  Everything is correctly assigned in that panel, but the actual/live view shows the incorrect include page, or it won't find the include page, and I received the pictured error.  When I revert to the Graffiti Cards view, all the allocations and assignments show up correctly.  Oddly, the assigned banner images in the horizontal cards are correctly retained as were assigned. However, the horizontal card presentation is not providing the expected outcome (below)

**To Reproduce**

In a test course... 
1. Create two or three Collections, each with 1 module.  
2. Create different include pages for each module. 
3. Assign the horizontal card presentation to each module.
4. Assign banner images and card information text, as is usual.
5. Save along the way, as needed 
6. Observe outcome: do the horizontal cards display correctly for each assigned module and collection?
7. _If the error appears_, suggest switching to Graffiti Cards presentation to verify that assigned module and include pages appear as assigned in that presentation (they do for me).  

**Expected behavior**
The expectation is that, if working properly, each Collection contains its assigned module(s), displayed in the assigned **horizontal card presentations** and information, and each Collection displays its assigned include page and banner images.

**Screenshots**
![image](https://github.com/djplaner/canvas-collections/assets/143226390/2f8892ae-8b19-4799-aa99-79dfb5d1f510)

**Desktop** 
 - Browser is latest version Firefox, also duplicated in latest MS Edge
 - CC version is 1.2.3
 - Platform is Win 10 Pro, version 22H2

I hope I've described the situation adequately.  If not, just let me know.

**Comment by djplaner** [comment]
Thank you for the detailed explanation.  I've been able to follow that and re-create the bug you've encountered.  I've also discovered that there are a few other ways this bug makes itself known.

In short, the horizontal cards representation doesn't appear to be visualising the correct modules for the collection. I'm looking into it now.

**Comment by djplaner** [comment]
It appears that the issue was created by an oversight on my part.  Fixing that and the issue seems resolved.  I'm going to generate a new release (1.2.4) which will have this fix.

When you have a chance, please let me know if this fix the problem you've encountered?

**Comment by omachado-id** [comment]
Thanks for your usual prompt attention to CC's teething pains.  I'm glad that you were able to determine the cause of the issue and how to resolve it.  I'll await your version update.  

Regards.

**Comment by djplaner** [comment]
Thank you for you patience.  Apologies for the delay, the release should have been done over the weekend. It is now available ([direct install/update link](https://github.com/djplaner/canvas-collections/raw/main/dist/canvas-collections.user.js))

**Comment by omachado-id** [comment]
No problem at all!  This update (to *v. 1.2.5*) resolved the reported issue for me.  Each collection now has its assigned horizontal card in its proper place, with the correct Include page, banner image and descriptive text that I'd applied.  I'd say this issue is **resolved.**  Thanks again for your efforts!
